name: CI

on:
  push:
    paths-ignore:
      - .editorconfig
      - .gitattributes
      - .gitignore
      - docs/**
      - README.md
  pull_request:
    paths-ignore:
      - .editorconfig
      - .gitattributes
      - .gitignore
      - docs/**
      - README.md

jobs:
  build-php:
    name: Build PHP
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions:
          - '7.4'
          - '8.0'
          - '8.1'
          - '8.2'
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: curl json mbstring
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install composer dependencies for PHP <= 8.1
        if: matrix.php-versions <= '8.1'
        run: |
          composer remove --dev infection/infection symplify/phpstan-rules --no-update
          composer install --prefer-dist --no-progress --no-suggest
      - name: Install composer dependencies for PHP 8.2
        if: matrix.php-versions == '8.2'
        run: |
          composer install --prefer-dist --no-progress --no-suggest --ignore-platform-req=php+
      - name: Run PHP linter
        run: |
          find . -name \*.php  ! -path "./vendor/*" -exec php -l {} \;
      - name: Run unit tests
        run: |
          make tests
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Setup PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: xdebug
          extensions: curl json mbstring
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install composer dependencies
        run: |
          composer update --prefer-dist --no-progress --no-suggest
      - name: Normalize composer.json
        run: |
          composer normalize --dry-run
      - name: Check coding standards
        run: |
          vendor/bin/ecs check --no-progress-bar
      - name: Generate code coverage
        run: |
          make code-coverage
      - name: Send code coverage report to coveralls.io
        run: |
          vendor/bin/php-coveralls -v
        env:
          COVERALLS_RUN_LOCALLY: 1
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      - name: Run mutation tests
        run: |
          make mutation
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
      - name: Run phpstan
        run: |
          make phpstan
      - name: Run rector
        run: |
          make rector-dry
